//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sity_marz2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class connect
    {
        public int con_id { get; set; }
        public Nullable<int> marz_id { get; set; }
        public Nullable<int> city_id { get; set; }
    
        public virtual city city { get; set; }
        public virtual marz marz { get; set; }
    }
}
